### ISSUE TITLE
Youtube Sight with a Brand Account ?

### ISSUE THREAD

**Issue by peter-power-594** [bkolicoski/ttc-tools#26]
Good Day,

When I tried to create a key for Youtube Sight with a brand account it didn't work.
Could you help me figure out what's wrong please ?

Step to reproduce :

1. Visit https://tools.tastethecode.com/youtube-sight/
2. Use a Gsuite email and select a "Brand Account"
3. I'm being redirected to this kind of url :

`https://tools.tastethecode.com/youtube-sight/auth?code=XXXXXX&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyt-analytics.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.readonly#
`

but the related key / token to be used is not displayed on the screen.

I was fully granted the access on the Youtube channel even if I'm not the original owner.

Thank you very much in advance for your time

Peter

**Comment by bkolicoski** [comment]
Hi Peter, 

There is nothing wrong with using the tool with a brand account as I use it for my own "brand" channel. The problem you are facing is caused by a limit in the usage quota that YouTube applied to my account for the project and I'm currently looking into ways of mitigating this so the tool can continue to operate normally. 

I don't know exactly when this will be resolved but for the time being, you can try the same at different times of day when the quota is reset and it should work. Once you have the GUID, the API calls should be unaffected. 

Sorry for the inconvenience and I'll keep you posted when the issue is resolved. 

Bill

**Comment by peter-power-594** [comment]
Thank you very much for the fast answer @bkolicoski 
No need to be sorry, it's already an awesome gem for a free tool :-)
For now I'm gonna retry at different interval of the day as you suggested me.
Same I'll try to keep you uptodate if it works.

**Comment by bkolicoski** [comment]
Hey @peter-attr this should now be fixed as I regained access to a quota from YT. Please give it a go once you can.

**Comment by peter-power-594** [comment]
Hey @bkolicoski you are the MAN OF THE SITUATION ! ! ! 
Thank you very much, I've successfully regain access to the data as well on my side. 
That was unexpected and a super start for 2022.

Happy new year and best wishes for 2022 Blagojce :-D
May the force be with you !
